# Generated by Django 3.2.18 on 2024-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20240715_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ac',
            field=models.BooleanField(default=False, verbose_name='Galadi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='called',
            field=models.BooleanField(default=False, verbose_name='Telefonni olmadi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Telefon urdim'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='wait',
            field=models.BooleanField(default=False, verbose_name='Galmidi'),
        ),
    ]
