# Generated by Django 4.2.14 on 2024-11-05 05:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_alter_contact_ac_alter_contact_directions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body_en',
            field=ckeditor.fields.RichTextField(verbose_name='English'),
        ),
    ]
